---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Backstage-website
  description: The backstage frontend interface
  annotations:
    backstage.io/techdocs-ref: dir:/docs
  links:
    - title: Backstage Prod
      url: https://backstage.puregym.com
    - title: Backstage Staging
      url: https://backstage.puregymuk.dev
spec:
  type: website
  owner: production_support_-_sre_team
  lifecycle: production
  system: backstage
  dependsOn:
    - resource:devtools-ne-aks
  consumesApi:
    - api:backstage-api

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: spotify
  description: The Spotify web API
  tags:
    - spotify
    - rest
  annotations:
    backstage.io/techdocs-ref: dir:/docs
    backstage.io/definition-at-location: 'url:https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/spotify.com/v1/swagger.yaml'
spec:
  type: openapi
  lifecycle: production
  owner: production_support_-_sre_team
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: Example-ADR
  description: An example ADR
  annotations:
    backstage.io/adr-location: /adrs
spec:
  type: website
  owner: production_support_-_sre_team
  lifecycle: production
  system: backstage

---