---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-api
  description: An example of a Backstage application.
  annotations:
    backstage.io/techdocs-ref: dir:/docs
spec:
  type: website
  owner: production_support_-_sre_team
  lifecycle: production
  system: backstage
  dependsOn:
    - resource:devtools-ne-aks
  definition: 
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml

---