---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DevOps
  annotations:
    dev.azure.com/project: "Infrastructure and tooling team Team"
    dev.azure.com/build-definition: "PGG Tenant IAC"
    jira/project-key: PG
  links:
  - url: https://dev.azure.com/Puregym/Infrastructure%20and%20tooling%20team
    title: "Infra and Tooling CI"
    icon: dashboard
spec:
  type: service
  owner: production_support_-_sre_team
  lifecycle: production
  system: backstage
  
---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: infra-demo-api
  links:
    - url: https://demo.pureiac.com/api/v1
      title: Root-API
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:/docs
spec:
  type: openapi
  lifecycle: experimental
  owner: developers_-_platform_team
  system: infrastructure-demo
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Test-API
      license:
        name: MIT
    servers:
      - url: http://demo.pureiac.com/api/v1
    paths:
      /test:
        get:
          summary: List all demo tests