---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Backstage-website
  description: The backstage frontend interface
  annotations:
    backstage.io/techdocs-ref: dir:/docs
  links:
    - title: Backstage Prod
      url: https://backstage.puregym.com
    - title: Backstage Staging
      url: https://backstage.puregymuk.dev
spec:
  type: website
  owner: production_support_-_sre_team
  lifecycle: production
  system: backstage
  dependsOn:
    - resource:devtools-ne-aks

---