---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DevOps
  annotations:
    dev.azure.com/project: "Infrastructure and tooling team Team"
    dev.azure.com/build-definition: "PGG Tenant IAC"
    jira/project-key: PG
  links:
  - url: https://dev.azure.com/Puregym/Infrastructure%20and%20tooling%20team
    title: "Infra and Tooling CI"
    icon: dashboard
spec:
  type: service
  owner: production_support_-_sre_team
  lifecycle: production
  system: backstage
  
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Backstage-website
  description: The backstage frontend interface
  annotations:
    backstage.io/techdocs-ref: dir:/docs
  links:
    - title: Backstage Prod
      url: https://backstage.puregym.com
    - title: Backstage Staging
      url: https://backstage.puregymuk.dev
spec:
  type: website
  owner: production_support_-_sre_team
  lifecycle: production
  system: backstage
  dependsOn:
    - resource:devtools-ne-aks
  consumesApi:
    - api:backstage-api