---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DevOps
  annotations:
    dev.azure.com/project-repo: "puregym/Infrastructure and tooling team"
  links:
  - url: https://dev.azure.com/Puregym/Infrastructure%20and%20tooling%20team
    title: "Infra and Tooling CI"
    icon: dashboard
spec:
  type: service
  owner: production_support_-_sre_team
  lifecycle: production
  system: backstage
  
---