---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DevOps
  annotations:
    dev.azure.com/project-repo: puregym/"Infrastructure and tooling team"
spec:
  type: service
  owner: production_support_-_sre_team
  lifecycle: production
  system: backstage
  
---