---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-api
  description: An example of a Backstage application.
  annotations:
    backstage.io/techdocs-ref: dir:/docs
spec:
  type: website
  owner: production_support_-_sre_team
  lifecycle: production
  system: backstage
  dependsOn:
    - resource:devtools-ne-aks

---