---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: infra-demo-api
  annotations:
    backstage.io/techdocs-ref: dir:/docs
spec:
  type: openapi
  lifecycle: experimental
  owner: developers_-_platform_team
  system: infrastructure-demo
  definition: 
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml

---