---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Backstage-website-test
  description: The backstage test
  annotations:
    backstage.io/techdocs-ref: dir:/docs
spec:
  type: website
  owner: production_support_-_sre_team
  lifecycle: production
  system: backstage
  dependsOn:
    - resource:devtools-ne-aks

---